### ISSUE TITLE
With your knowledge, could you also make an 'Enable Windows Defender' ?

### ISSUE THREAD

**Issue by HenkPoley** [NYAN-x-CAT/Disable-Windows-Defender#2]

**Comment by KiExitDispatcher** [comment]
Its same lol, just change the values. if you have 2 braincells you will know how.

**Comment by HenkPoley** [comment]
Ah, sorry. 4 years ago I was attempting revive some Windows install with a broken Windows Defender.

Under Windows Server you can ask it to uninstall Defender, do some more manual cleanups (I guess), and reinstall it. And it would probably work again.

I understand that it's a silly question in the context of this repo. That's why I already closed the ticket.

**Comment by KiExitDispatcher** [comment]
😄 nw.
